project:
  type: book

book:
  title: "Curso Overleaf 2025"
  author: "Ítalo Sánchez Bermúdez"
  date: "20/1/2025"
  chapters:
    - index.qmd
    - paqueterias.qmd
    - primerdoc.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt



